// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACaO2MzlVeolPl1MrdV-uKVGFhf0umxcE',
    appId: '1:153383158944:android:b4c570c9b1df9fd051f5c5',
    messagingSenderId: '153383158944',
    projectId: 'password-manager-3c914',
    storageBucket: 'password-manager-3c914.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEwp-mjCy8BVrM0q2uyuN68eRTtX2die8',
    appId: '1:153383158944:ios:498da2949fc1171351f5c5',
    messagingSenderId: '153383158944',
    projectId: 'password-manager-3c914',
    storageBucket: 'password-manager-3c914.firebasestorage.app',
    iosBundleId: 'com.example.passwords',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD3qmSXO0lPK0nsKeW_gQQCPSTpWqT64U',
    appId: '1:153383158944:web:a3cfac563d52074f51f5c5',
    messagingSenderId: '153383158944',
    projectId: 'password-manager-3c914',
    authDomain: 'password-manager-3c914.firebaseapp.com',
    storageBucket: 'password-manager-3c914.firebasestorage.app',
  );

}